### ISSUE TITLE
Add Redis database dump

### ISSUE THREAD

**Issue by lukepighetti** [stockholmux/ecommerce-sample-set#1]
Hi there,

I'm following along your tutorial listed here https://medium.com/@stockholmux/from-sql-to-redis-chapter-1-145c82e4baa0

It would be nice to have access to a Redis instance with your data already in it. I believe `redis-commander` has the ability to import/export Redis databases. I know it's a big ask but if you happen to have easy access to do this it would be appreciated. If not, I understand, no worries.

By the way, your tutorial is really good. Thanks for sharing it.

**Comment by stockholmux** [comment]
I'd suggest using the script. Redis exports don't work well across versions, so this is an evergreen approach.

**Comment by lukepighetti** [comment]
Alright, no problem. Thanks again!
